BookStore/Models/Sach.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookStore.Models
{
    public class Sach
    {
        internal object EnrollmentDate;
        public int ID { get; set; }


        [Required(ErrorMessage = "Thể loại không được bỏ trống!")]
		[Display(Name = "Thể Loại")]
		public int TheLoaiID { get; set; }


        [Required(ErrorMessage = "Tên nhà xuất bản không được bỏ trống!")]
		[Display(Name = "Nhà Xuất Bản")]
		public int NhaSanXuatID { get; set; }

		[Required(ErrorMessage = "Tên tác giả không được bỏ trống!")]
		[Display(Name = "Tác Giả")]
		public int TacGiaID { get; set; }


		[StringLength(250)]
        [Required(ErrorMessage = "Tên sách không được bỏ trống!")]
		[Display(Name = "Tên Sản Phẩm")]
		public string TenSach { get; set; }


        
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Đơn giá không được bỏ trống!")]
		[Display(Name = "Đơn Giá")]
		public int DonGia { get; set; }


        [StringLength(255)]
        public string? AnhBia { get; set; }
		//Tạo trường thông tin mới để lưu dữ liệu ảnh
		[NotMapped]
		[Display(Name = "Hình ảnh sản phẩm")]
		public IFormFile? DuLieuHinhAnh { get; set; }


		/*[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Ngày nhập hàng không được bỏ trống!")]
        public DateTime NgayNhap { get; set; }*/



		[DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Số lượng không được bỏ trống!")]
		[Display(Name = "Số Lượng")]
		public int SoLuong {  get; set; }


        [Column(TypeName = "ntext")]
        [DataType(DataType.MultilineText)]
		[Display(Name = "Mô Tả")]
		public string? MoTa { get; set; }


        public ICollection<DonHang_ChiTiet>? DonHang_ChiTiet { get; set; }
        public TheLoai? TheLoai { get; set; }
        public NhaSanXuat? NhaSanXuat { get; set; }
		public TacGia? TacGia { get; set; }

    }

	[NotMapped]
	public class PhanTrangSanPham
	{
		public int TrangHienTai { get; set; }
		public int TongSoTrang { get; set; }
		public List<Sach> Sach { get; set; }
		public bool HasPreviousPage => TrangHienTai > 1;
		public bool HasNextPage => TrangHienTai < TongSoTrang;
	}
}

BookStore/Areas/Admin/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookStore.Models;
using Slugify;
using System.Linq.Dynamic.Core;
using Microsoft.Extensions.Hosting;
using Microsoft.IdentityModel.Logging;
using Microsoft.AspNetCore.Authorization;

namespace BookStore.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = "Admin")]
	public class SachController : Controller
    {
        private readonly BookStoreDBContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public SachController(BookStoreDBContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // GET: Sach
        public async Task<IActionResult> Index()
        {
            return View();
        }

        // GET: SanPham/Index_LoadData
        public IActionResult Index_LoadData()
        {
            try
            {
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                var searchValue = Request.Form["search[value]"].FirstOrDefault();
                int pageSize = length != null ? int.Parse(length) : 0;
                int skip = start != null ? int.Parse(start) : 0;
                int totalRecords = 0;
                int filterRecords = 0;
                var sach = from r in _context.Sach
                           select new
                           {
                               ID = r.ID,
                               AnhBia = r.AnhBia,
                               TenTheLoai = r.TheLoai.TenTheLoai,
                               TenNhaSanXuat = r.NhaSanXuat.TenNhaSanXuat,
                               TenTacGia = r.TacGia.TenTacGia,
                               TenSach = r.TenSach,
                               SoLuong = r.SoLuong,
                               DonGia = r.DonGia
                              };
                totalRecords = sach.Count();
                // Sắp xếp
                if (!string.IsNullOrEmpty(sortColumn) && !string.IsNullOrEmpty(sortColumnDirection))
                {
                    sach = sach.OrderBy(sortColumn + " " + sortColumnDirection);
                }
                // Tìm kiếm
                if (!string.IsNullOrEmpty(searchValue) && !string.IsNullOrWhiteSpace(searchValue))
                {
                    sach = sach.Where(r => r.TenTheLoai.Contains(searchValue) ||
                    r.TenNhaSanXuat.Contains(searchValue) ||
					r.TenTacGia.Contains(searchValue) ||
					r.TenSach.Contains(searchValue) ||
                    r.SoLuong.ToString().Contains(searchValue) ||
                    r.DonGia.ToString().Contains(searchValue));
                }
                filterRecords = sach.Count();
                var data = sach.Skip(skip).Take(pageSize).ToList();
                var jsonData = new
                {
                    draw = draw,
                    recordsFiltered = filterRecords,
                    recordsTotal = totalRecords,
                    data = data
                };
                return Json(jsonData, new System.Text.Json.JsonSerializerOptions());
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    

// GET: Sach/Details/5
public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Sach == null)
            {
                return NotFound();
            }

            var sach = await _context.Sach
                .Include(s => s.NhaSanXuat)
                .Include(s => s.TheLoai)
			    .Include(s => s.TacGia)
				.FirstOrDefaultAsync(m => m.ID == id);
            if (sach == null)
            {
                return NotFound();
            }

            return View(sach);
        }

        // GET: Sach/Create
        public IActionResult Create()
        {
            ViewData["NhaSanXuatID"] = new SelectList(_context.NhaSanXuat, "ID", "TenNhaSanXuat");
            ViewData["TheLoaiID"] = new SelectList(_context.TheLoai, "ID", "TenTheLoai");
			ViewData["TacGiaID"] = new SelectList(_context.TacGia, "ID", "TenTacGia");
			return View();
        }

        // POST: Sach/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,TheLoaiID,NhaSanXuatID,TacGiaID,TenSach,DonGia,DuLieuHinhAnh,SoLuong,MoTa")] Sach sach)
        {
            if (ModelState.IsValid)
            {
				string path = "";
				// Nếu hình ảnh không bỏ trống thì upload
				if (sach.DuLieuHinhAnh != null)
				{
					string wwwRootPath = _hostEnvironment.WebRootPath;
					string folder = "/uploads/";
					string fileExtension = Path.GetExtension(sach.DuLieuHinhAnh.FileName).ToLower();
					string fileName = sach.TenSach;

					SlugHelper slug = new SlugHelper();
					string fileNameSluged = slug.GenerateSlug(fileName);

					path =   fileNameSluged + fileExtension;
					string physicalPath = Path.Combine(wwwRootPath + folder, fileNameSluged + fileExtension);
					using (var fileStream = new FileStream(physicalPath, FileMode.Create))
					{
						await sach.DuLieuHinhAnh.CopyToAsync(fileStream);
					}
				} 
                // Cập nhật đường dẫn vào CSDL
                sach.AnhBia = path ?? null;

				_context.Add(sach);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["NhaSanXuatID"] = new SelectList(_context.NhaSanXuat, "ID", "TenNhaSanXuat", sach.NhaSanXuatID);
            ViewData["TheLoaiID"] = new SelectList(_context.TheLoai, "ID", "TenTheLoai", sach.TheLoaiID);
			ViewData["TacGiaID"] = new SelectList(_context.TacGia, "ID", "TenTacGia", sach.TacGiaID);
			return View(sach);
        }

        // GET: Sach/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Sach == null)
            {
                return NotFound();
            }

            var sach = await _context.Sach.FindAsync(id);
            if (sach == null)
            {
                return NotFound();
            }
            ViewData["NhaSanXuatID"] = new SelectList(_context.NhaSanXuat, "ID", "TenNhaSanXuat", sach.NhaSanXuatID);
            ViewData["TheLoaiID"] = new SelectList(_context.TheLoai, "ID", "TenTheLoai", sach.TheLoaiID);
			ViewData["TacGiaID"] = new SelectList(_context.TacGia, "ID", "TenTacGia", sach.TacGiaID);
			return View(sach);
        }

        // POST: Sach/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,TheLoaiID,NhaSanXuatID,TacGiaID,TenSach,DonGia,DuLieuHinhAnh,SoLuong,MoTa")] Sach sach)
        {
            if (id != sach.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string path = "";

                    // Nếu hình ảnh không bỏ trống thì upload ảnh mới

                    if (sach.DuLieuHinhAnh != null)
                    {
                        string wwwRootPath = _hostEnvironment.WebRootPath;
                        string folder = "/uploads/";
                        string fileExtension = Path.GetExtension(sach.DuLieuHinhAnh.FileName).ToLower();

                        string fileName = sach.TenSach;
                        SlugHelper slug = new SlugHelper();
                        string fileNameSluged = slug.GenerateSlug(fileName);
                        path = fileNameSluged + fileExtension;

                        string physicalPath = Path.Combine(wwwRootPath + folder, fileNameSluged + fileExtension);

                        using (var fileStream = new FileStream(physicalPath, FileMode.Create))
                        {
                            await sach.DuLieuHinhAnh.CopyToAsync(fileStream);
                        }
                    }
                    _context.Update(sach);

                    if (string.IsNullOrEmpty(path))

                        _context.Entry(sach).Property(x => x.AnhBia).IsModified = false;
                    else
                        sach.AnhBia = path;
                    await _context.SaveChangesAsync();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SachExists(sach.ID))

                    {

                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["NhaSanXuatID"] = new SelectList(_context.NhaSanXuat, "ID", "TenNhaSanXuat", sach.NhaSanXuatID);
            ViewData["TheLoaiID"] = new SelectList(_context.TheLoai, "ID", "TheLoai", sach.TheLoaiID);
			ViewData["TacGiaID"] = new SelectList(_context.TacGia, "ID", "TacGia", sach.TacGiaID);
			return View(sach);
        }

        // GET: Sach/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {

BookStore/Controllers/SachController.cs
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SlugGenerator;
using Slugify;

namespace BookStore.Controllers
{
	public class SachController : Controller
	{
		private readonly BookStoreDBContext _context;
		public SachController(BookStoreDBContext context)
		{
			_context = context;
		}
		// GET: Index
		public IActionResult Index(int? trang)
		{
			var danhSach = LayDanhSachSanPham(trang ?? 1);
			if (danhSach.Sach.Count == 0)
				return NotFound();
			else
				return View(danhSach);
		}
	private PhanTrangSanPham LayDanhSachSanPham(int trangHienTai)
		{
			int maxRows = 20;
			PhanTrangSanPham phanTrang = new PhanTrangSanPham();
			phanTrang.Sach = _context.Sach
			.Include(s => s.NhaSanXuat)
			.Include(s => s.TheLoai)
			.OrderBy(r => r.TheLoaiID)
			.Skip((trangHienTai - 1) * maxRows)
			.Take(maxRows).ToList();
			decimal tongSoTrang = Convert.ToDecimal(_context.Sach.Count()) / Convert.ToDecimal(maxRows);
			phanTrang.TongSoTrang = (int)Math.Ceiling(tongSoTrang);
			phanTrang.TrangHienTai = trangHienTai;
			return phanTrang;
		}

		// GET: PhanLoai
		public IActionResult PhanLoai(int? trang, string tenLoai)
		{
			var danhSachPhanLoai = LayDanhSachSanPhamTheoPhanLoai(trang ?? 1, tenLoai);
			if (danhSachPhanLoai.Sach.Count == 0)
				return NotFound();
			else
				return View(danhSachPhanLoai);
		}
		private PhanTrangSanPham LayDanhSachSanPhamTheoPhanLoai(int trangHienTai, string tenLoai)
		{
			int maxRows = 20;
			SlugHelper slug = new SlugHelper();
			var sanPhamPhanLoai = _context.Sach
			.Include(s => s.NhaSanXuat)
			.Include(s => s.TheLoai)
			.AsEnumerable().Where(r => slug.GenerateSlug(r.TheLoai.TenTheLoai) == tenLoai);
			PhanTrangSanPham phanTrang = new PhanTrangSanPham();
			phanTrang.Sach = sanPhamPhanLoai.OrderBy(r => r.TheLoaiID)
			.Skip((trangHienTai - 1) * maxRows)
			.Take(maxRows).ToList();
			decimal tongSoTrang = Convert.ToDecimal(sanPhamPhanLoai.Count()) / Convert.ToDecimal(maxRows);
			phanTrang.TongSoTrang = (int)Math.Ceiling(tongSoTrang);
			phanTrang.TrangHienTai = trangHienTai;
			return phanTrang;
		}

		// GET: ChiTiet
		public IActionResult ChiTiet(string tenSach)
		{
		
			var sanPham = _context.Sach
			.Include(s => s.NhaSanXuat)
			.Include(s => s.TheLoai)
			.AsEnumerable().Where(r => r.TenSach.GenerateSlug() == tenSach).SingleOrDefault();
			if (sanPham == null)
				return NotFound();
			else
				return View(sanPham);
		}

	}
}

BookStore/Views/Sach/ChiTiet.cshtml
@model BookStore.Models.Sach
@{
	ViewData["Title"] = Model.TenSach;
}

<div class="page-title-overlap bg-dark pt-4">
	<div class="container d-lg-flex justify-content-between py-2 py-lg-3">
		<div class="order-lg-2 mb-3 mb-lg-0 pt-lg-2">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb breadcrumb-light flex-lg-nowrap justify-content-center justify-content-lg-start">
					<li class="breadcrumb-item">
						<a class="text-nowrap" asp-area="" asp-controller="Home" asp-action="Index"><i class="ci-home"></i>Trang chủ</a>
					</li>
					<li class="breadcrumb-item text-nowrap">
						<a asp-area="" asp-controller="Sach" asp-action="Index">Sản phẩm</a>
					</li>
					<li class="breadcrumb-item text-nowrap active" aria-current="page">Chi tiết</li>
				</ol>
			</nav>
		</div>
		<div class="order-lg-1 pe-lg-4 text-center text-lg-start">
			<h1 class="h3 text-light mb-0">@ViewData["Title"]</h1>
		</div>
	</div>
</div>
<div class="container">
	<div class="bg-light shadow-lg rounded-3 px-4 py-3 mb-5">
		<div class="px-lg-3">
			<div class="row">
				<div class="col-lg-7 pe-lg-0 pt-lg-4">
					<div class="product-gallery">
						<div class="product-gallery-preview order-sm-2">
							<div class="product-gallery-preview-item active" id="first">
								<img class="image-zoom" src="~/uploads/@Model.AnhBia" data-zoom="~/uploads/@Model.AnhBia" width="300" />
								<div class="image-zoom-pane"></div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-5 pt-4 pt-lg-0">
					<div class="product-details ms-auto pb-3">
						<div class="d-flex justify-content-between align-items-center mb-2">
							<a href="#reviews" data-scroll>
								<div class="star-rating">
									<i class="star-rating-icon ci-star-filled active"></i>
									<i class="star-rating-icon ci-star-filled active"></i>
									<i class="star-rating-icon ci-star-filled active"></i>
									<i class="star-rating-icon ci-star-filled active"></i>
									<i class="star-rating-icon ci-star"></i>
								</div>
								<span class="d-inline-block fs-sm text-body align-middle mt-1 ms-1">74 đánh giá</span>
							</a>
						</div>
						<div class="mb-3">
							<span class="h3 fw-normal text-accent me-1">@string.Format("{0:N0}", Model.DonGia)<small>đ</small></span>
						</div>
						<div class="mb-3">
							<a class="btn btn-primary btn-shadow d-block w-100" asp-area="" asp-controller="GioHang" asp-action="Them" asp-route-id="@Model.ID">
								<i class="ci-cart fs-lg me-2"></i>Thêm vào giỏ hàng
							</a>
						</div>
						<div class="accordion mb-3" id="productPanels">
							<div class="accordion-item">
								<h3 class="accordion-header">
									<a class="accordion-button" href="#productInfo" role="button" data-bs-toggle="collapse" aria-expanded="true" aria-controls="productInfo">
										<i class="ci-announcement text-muted fs-lg align-middle mt-n1 me-2"></i>Thông tin cơ bản sách
									</a>
								</h3>
								<div class="accordion-collapse collapse show" id="productInfo" data-bs-parent="#productPanels">
									<div class="accordion-body">
										<p></p>
									</div>
								</div>
							</div>
							<div class="accordion-item">
								@*@<h3 class="accordion-header">
									<a class="accordion-button collapsed" href="#shippingOptions" role="button" data-bs-toggle="collapse" aria-expanded="true" aria-controls="shippingOptions">
										<i class="ci-settings text-muted lead align-middle mt-n1 me-2"></i>Thông số kỹ thuật
									</a>
								</h3>*@
								<div class="accordion-collapse collapse" id="shippingOptions" data-bs-parent="#productPanels">
									<div class="accordion-body">
										<p></p>
									</div>
								</div>
							</div>
							<div class="accordion-item">
								<h3 class="accordion-header">
									<a class="accordion-button collapsed" href="#localStore" role="button" data-bs-toggle="collapse" aria-expanded="true" aria-controls="localStore">
										<i class="ci-package text-muted fs-lg align-middle mt-n1 me-2"></i>Hình thức đóng gói
									</a>
								</h3>
								<div class="accordion-collapse collapse" id="localStore" data-bs-parent="#productPanels">
									<div class="accordion-body">
										<p></p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row align-items-center py-md-3">
		<div class="col-12 py-4">
			<h2 class="h3 mb-4 pb-2">Giới thiệu chi tiết sản phẩm</h2>
			<p class="text-muted pb-2" style="text-align:justify">@(Model.MoTa ?? "Chưa có mô tả về sản phẩm.")</p>
		</div>
	</div>
</div>
<div class="border-top my-lg-3 py-5">
	<div class="container pt-md-2" id="reviews">
		<div class="row pb-3">
			<div class="col-lg-4 col-md-5">
				<h2 class="h3 mb-4">74 đánh giá</h2>
				<div class="star-rating me-2">
					<i class="ci-star-filled fs-sm text-accent me-1"></i>
					<i class="ci-star-filled fs-sm text-accent me-1"></i>
					<i class="ci-star-filled fs-sm text-accent me-1"></i>
					<i class="ci-star-filled fs-sm text-accent me-1"></i>
					<i class="ci-star fs-sm text-muted me-1"></i>
				</div>
				<span class="d-inline-block align-middle">4.1 điểm</span>
				<p class="pt-3 fs-sm text-muted">58 trong tổng số 74 (77%)<br>Khách hàng đã đề nghị mua sản phẩm này.</p>
			</div>
			<div class="col-lg-8 col-md-7">
				<div class="d-flex align-items-center mb-2">
					<div class="text-nowrap me-3">
						<span class="d-inline-block align-middle text-muted">5</span>
						<i class="ci-star-filled fs-xs ms-1"></i>
					</div>
					<div class="w-100">
						<div class="progress" style="height:4px;">
							<div class="progress-bar bg-success" role="progressbar" style="width:60%;" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
						</div>
					</div>
					<span class="text-muted ms-3">43</span>
				</div>
				<div class="d-flex align-items-center mb-2">
					<div class="text-nowrap me-3">
						<span class="d-inline-block align-middle text-muted">4</span>
						<i class="ci-star-filled fs-xs ms-1"></i>
					</div>
					<div class="w-100">
						<div class="progress" style="height:4px;">
							<div class="progress-bar" role="progressbar" style="width:27%;background-color:#a7e453;" aria-valuenow="27" aria-valuemin="0" aria-valuemax="100"></div>
						</div>
					</div>
					<span class="text-muted ms-3">16</span>
				</div>
				<div class="d-flex align-items-center mb-2">
					<div class="text-nowrap me-3">
						<span class="d-inline-block align-middle text-muted">3</span>
						<i class="ci-star-filled fs-xs ms-1"></i>
					</div>
					<div class="w-100">
						<div class="progress" style="height:4px;">
							<div class="progress-bar" role="progressbar" style="width:17%;background-color:#ffda75;" aria-valuenow="17" aria-valuemin="0" aria-valuemax="100"></div>
						</div>
					</div>
					<span class="text-muted ms-3">9</span>
				</div>
				<div class="d-flex align-items-center mb-2">
					<div class="text-nowrap me-3">
						<span class="d-inline-block align-middle text-muted">2</span>
						<i class="ci-star-filled fs-xs ms-1"></i>
					</div>
					<div class="w-100">
						<div class="progress" style="height:4px;">
							<div class="progress-bar" role="progressbar" style="width:9%;background-color:#fea569;" aria-valuenow="9" aria-valuemin="0" aria-valuemax="100"></div>
						</div>
					</div>
					<span class="text-muted ms-3">4</span>
				</div>
				<div class="d-flex align-items-center">
					<div class="text-nowrap me-3">
						<span class="d-inline-block align-middle text-muted">1</span>
						<i class="ci-star-filled fs-xs ms-1"></i>
					</div>
					<div class="w-100">
						<div class="progress" style="height: 4px;">
							<div class="progress-bar bg-danger" role="progressbar" style="width:4%;" aria-valuenow="4" aria-valuemin="0" aria-valuemax="100"></div>
						</div>
					</div>
					<span class="text-muted ms-3">2</span>
				</div>
			</div>
		</div>
	</div>
</div>